### ISSUE TITLE
地址提取

### ISSUE THREAD

**Issue by x19990416** [wzc570738205/address-smart-parse#3]
比如 浙江绍兴市越城区东湖街道柏舍村庙湾46号（不要放横河小店，放就投诉）[1211]，其中 1211这个编码是需要的我看都被删除了，请问有啥办法保留吗

**Comment by wzc570738205** [comment]
`浙江绍兴市越城区东湖街道柏舍村庙湾46号（不要放横河小店放就投诉1211` 目前是使用特殊字符分割的，建议这么处理
